name: 📚 Documentation
description: Report an issue or suggest an improvement to documentation
title: "[Documentation]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us improve our documentation!

  - type: dropdown
    id: type
    attributes:
      label: Documentation Issue Type
      description: What kind of documentation issue are you reporting?
      options:
        - Error or inaccuracy
        - Missing documentation
        - Unclear documentation
        - Outdated documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation issue located? Provide links or file paths if possible.
      placeholder: |
        URL, README.md, or other location...
      render: markdown
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: Describe the issue with the current documentation
      placeholder: |
        The current documentation says... but it should be...
      render: markdown
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Fix
      description: If you have a suggestion for how to fix the issue, please describe it here
      placeholder: |
        I suggest changing/adding...
      render: markdown
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the documentation issue here
      placeholder: |
        More information that might be helpful...
      render: markdown
    validations:
      required: false

  - type: checkboxes
    id: existing-issues
    attributes:
      label: Is this issue already reported?
      description: Please search existing issues before creating a new one
      options:
        - label: I have searched the existing issues and this has not been reported yet
          required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT_URL)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
