name: 💡 Feature Request
description: Suggest a new feature for this project
title: "[Feature Request]: "
labels: ["feature request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve?
      placeholder: |
        It's hard when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: |
        I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: |
        I've tried using... or I've considered...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here
      placeholder: |
        More details that might help understand the request...
    validations:
      required: false

  - type: textarea
    id: debug-info
    attributes:
      label: Platform info
      description: Run `poof debug` and paste the output here.
      render: shell
    validations:
      required: true

  - type: checkboxes
    id: existing-issues
    attributes:
      label: Is this issue already reported?
      description: Please search existing issues before creating a new one
      options:
        - label: I have searched the existing issues and this has not been reported yet
          required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT_URL)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
