name: Security audit

on:
  push:
    branches:
      - pre/**
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    branches:
      - main
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
  schedule:
    - cron: '0 0 * * 1' # Every Monday at midnight
  workflow_dispatch:

permissions:
  issues: write
  checks: write
  contents: read
  pull-requests: write

jobs:
  security_audit:
    name: Security audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          rustflags: ""
      - name: Securty audit
        uses: pirafrank/audit-check-action@main

