name: Test Poof

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Repo to get"
        required: true
        default: "user/repo"

jobs:
    test_with_stable:
      name: Install ${{ github.event.inputs.repo }} with latest stable release
      runs-on: ubuntu-latest
      steps:
        - name: Setup poof
          run: |
            curl -fsSL https://raw.githubusercontent.com/pirafrank/poof/main/install.sh | sh

        - name: Add to PATH
          run: |
            echo "$HOME/.local/bin" >> "$GITHUB_PATH"
            echo "$HOME/.local/share/poof/bin" >> "$GITHUB_PATH"

        - name: Test installed poof
          run: poof --version

        - name: Install ${{ github.event.inputs.repo }}
          run: |
            poof install ${{ github.event.inputs.repo }}
            ls -la

    test_with_main:
      name: Install ${{ github.event.inputs.repo }} with main branch
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Setup Rust
          uses: actions-rust-lang/setup-rust-toolchain@v1

        - name: Add to PATH
          run: |
            echo "$HOME/.local/share/poof/bin" >> "$GITHUB_PATH"

        - name: Test installed poof
          run: cargo run --bin poof -- --version

        - name: Install ${{ github.event.inputs.repo }}
          run: |
            cargo run --bin poof -- install ${{ github.event.inputs.repo }}
            ls -la
